version: "3.6"

services:
  {{ .Name }}:
    build: {{ .Name }}
    ports:
      - {{ .Parameters.externalPort }}:8080
    environment:
      - CONNECTION_STRING_PATH=/run/secrets/mongo-connection-string
    secrets:
      - source: mongo-connection-string
        target: mongo-connection-string