version: "3.6"

services:
  {{ .Name }}:
    build: {{ .Name }}
    ports:
      - {{ .Parameters.externalPort }}:8080
    secrets:
      - source: mongo-connection-string
        target: /app/config/mongo-connection-string